import type { Metadata } from "next";
import { Geist, Geist_Mono, M_PLUS_2 } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import Footer from "@/app/footer";
import Providers from "./providers";
import Toolbar from "./toolbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const mplus2 = M_PLUS_2({
  subsets: ["latin"],
  variable: "--font-mplus2",
  weight: "variable"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  applicationName:"BlackInkPaper",
  // viewport:{
  //   initialScale:0.9,
  //   width:'device-width',
  //   interactiveWidget:"overlays-content",
  //   minimumScale:0.4,
  // }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${mplus2.variable} antialiased font-display`}>
        <Providers>
          <Navbar />
          <Toolbar/>
          <main className="pt-8"> {children} </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
